[tool.black]
target-version = ["py310", "py311", "py312", "py313", "py314"]
# Keep exclude in sync with flake8 config in tox.ini
exclude = '''
/(
      \.git
    | \.tox
    | node_modules
    | __pycache__
    | libs
    | \*\.pyc
    | \.cache
    | \.eggs
    | .*\.egg
    | .*\.egg-info
    | env
    | venv
    | \..*venv
    | \.serverless
)/
'''
